 
datasource:
  db:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}d9a7e32dadf04cc84cd11e21faf41d43a6e3690e2305fb9f9e7c646af719c818'

yoke:
  notify:
    url: http://localhost:8082/event
