spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}fc9f773e6df583df9d7bad1f74b14e6fc8190c0ae50b1fa0d173cf81e6b00041'

yoke:
  notify:
    url: http://localhost:8082/event
