spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}ee6bcb18201cdbf8a280702eff0c7b717bd8c03e4874b5fce744537e8a9a493c'

yoke:
  notify:
    url: http://localhost:8082/event
